<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitbe73b15ddb6b2386c8f4d5e481a74773
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Sabbir\\TinyPopup\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Sabbir\\TinyPopup\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Sabbir\\TinyPopup\\Base' => __DIR__ . '/../..' . '/app/Base.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitbe73b15ddb6b2386c8f4d5e481a74773::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitbe73b15ddb6b2386c8f4d5e481a74773::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitbe73b15ddb6b2386c8f4d5e481a74773::$classMap;

        }, null, ClassLoader::class);
    }
}
